version: '3.8'

services:
  polymarket-agent-api:
    container_name: polymarket-agent-api
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn http_api:app --host 0.0.0.0 --port ${PORT:-8000} --workers ${WORKERS:-1}
    environment:
      - PORT=${PORT:-8000}
      - WORKERS=${WORKERS:-1}
      - PYTHONPATH=/polymarket-agent
      - PYTHONUNBUFFERED=1
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s